package com.jagwasi.presentation.governance
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.jagwasi.core.EncryptedPreferences
import com.jagwasi.data.local.entity.AuditEntry
import com.jagwasi.data.local.entity.Staff
import com.jagwasi.data.repository.AuditEntryRepository
import com.jagwasi.data.repository.StaffRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import java.security.MessageDigest
import kotlin.random.Random
