package com.jagwasi.presentation.order
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.jagwasi.data.local.entity.Order
import com.jagwasi.data.local.entity.Payment
import com.jagwasi.data.repository.OrderRepository
import com.jagwasi.domain.usecase.CreateOrderUseCase
import com.jagwasi.domain.usecase.DetectUnpaidExitUseCase
import com.jagwasi.domain.usecase.GenerateReceiptUseCase
import com.jagwasi.domain.usecase.ProcessPaymentUseCase
import com.jagwasi.domain.usecase.Result
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
